apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-order
spec:
  replicas: 5
  selector:
    matchLabels:
      app: parts-order
  template:
    metadata:
      labels:
        app: parts-order
    spec:    
      containers:
        - name: parts-order
          image: noknok79/parts-order:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: parts-order
spec:
  type: NodePort
  selector:
    app: parts-order
  ports:
    - port: 80
      targetPort: 80
