trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      terraform init
      terraform validate
    displayName: 'Terraform Initialization and Validation'

  - script: |
      terraform plan -out=tfplan
    displayName: 'Terraform Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: '<your_kubernetes_service_connection>'
      manifests: |
        $(System.DefaultWorkingDirectory)/path/to/kubernetes.yaml
    displayName: 'Deploy Kubernetes YAML'
