apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: parts-web
  template:
    metadata:
      labels:
        app: parts-web
    spec:
      containers:
        - name: parts-web
          image: noknok79/parts-web:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: parts-web
spec:
  type: LoadBalancer
  selector:
    app: parts-web
  ports:
    - port: 80
      targetPort: 80

--- 
apiVersion: v1
data: 
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lVWnJzU2M3OVhjbVc2L3hDV2paT0xFSzFQMXl3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FjR0Z5ZEhOMWJteHBiV2wwWldRdVkyeHZkV1J1Y3k1aWFYb3dIaGNOTWpRdwpNVEF5TVRRek5ETXpXaGNOTWpVd01UQXhNVFF6TkRNeldqQWxNU013SVFZRFZRUUREQnB3WVhKMGMzVnViR2x0CmFYUmxaQzVqYkc5MVpHNXpMbUpwZWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUw1d2c0WFpYWHNlaUQ1RVN5SG5TOEdCZ1pOb0RGN2pQYUoxOWxLd2pHQVZCb085Nm95RmZEbytTOElhMnYvegpWc1RzdE5qRXp4eTFPZjVBUnZsTHcxUzZYR01tRnZhUk1CaU0vUXV4NFg4b1pQanBGZ2liRXIvVFgxYkErQjNiCmVicnBGa2pJTVlKWTVlckxFMWRYWU8rWHpPTTh0VFBqNncxb1ZMbEFpc0trWWZ2elZ6cWs2TVd5dzBtRUJ0VGMKbXF5and0MG1DaFp5a2NBZit2MklFM0ZwRExiMkVaaVFXVEFLeXNJdVhXK0dISTZBYkM2clROZUV5c29BZUtsTQprMlVqZVRId2dDMTZMSFAyZlY3bWY3eWJ4NUVZTy9XWmpqNEZwdGZNeWxSTTQwWE4rejVxcTRLZTA4SG9tVnNuCjdzSFcwRjlQdFJLdFF2cWY4cS9jcExzQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZIUm0rSGZjVnVJMUpSZUMKOEs5Y21xajIvWG03TUI4R0ExVWRJd1FZTUJhQUZIUm0rSGZjVnVJMUpSZUM4SzljbXFqMi9YbTdNQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFmOEFRRmJjUTJUU2NYNy9FYkNSdklYClBXQTJ1aHJiN2xzUDRHTlNBOTNYMjVBVXN2VllqVWpMQ0lzZlJ0TkhFK3ZSTFo2ZUpkY0ZxaXRKbUZDT3VCODIKK0h4Z1QxWlRzYUJOMXRvajI1cWkwSUVWQ1B2QVNVQVliSEhpTDZLWDJCZExwdEhITnBydll0TlV4dEcrWDNhWQpXTm9vTGloeS9QUFpPTCtZdHZnc0hudjhRRHBETnNvdEwrVFh5cFB2VlE2eGRaTlI4bjNTb05aYVl5Z0ZKT1hpCnIwQVhHVWlKcndHS2hld3o5Qms4a0hCTk4yRU1zT0dGaVV2T3gxSU5hMUlOR1VocjROU1NZTVlqSStvK0lSNlMKaWNsWlpOT0Q3SFFzMitNbFE1U0xGTHFlRkRsT1JnUlVEWCtHNzJNRnJ3dGZMa0ZWRjZadStTWlQzUVBqTkZZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQytjSU9GMlYxN0hvZysKUkVzaDUwdkJnWUdUYUF4ZTR6MmlkZlpTc0l4Z0ZRYUR2ZXFNaFh3NlBrdkNHdHIvODFiRTdMVFl4TThjdFRuKwpRRWI1UzhOVXVseGpKaGIya1RBWWpQMExzZUYvS0dUNDZSWUlteEsvMDE5V3dQZ2QyM202NlJaSXlER0NXT1hxCnl4TlhWMkR2bDh6alBMVXo0K3NOYUZTNVFJckNwR0g3ODFjNnBPakZzc05KaEFiVTNKcXNvOExkSmdvV2NwSEEKSC9yOWlCTnhhUXkyOWhHWWtGa3dDc3JDTGwxdmhoeU9nR3d1cTB6WGhNcktBSGlwVEpObEkza3g4SUF0ZWl4ego5bjFlNW4rOG04ZVJHRHYxbVk0K0JhYlh6TXBVVE9ORnpmcythcXVDbnRQQjZKbGJKKzdCMXRCZlQ3VVNyVUw2Cm4vS3YzS1M3QWdNQkFBRUNnZ0VBTE1Gd2g0SmdEOUZMSDZjWktTeWNoeXVTY2p3ZnZDVVhsUmkzL1JMMHlwZm0KWWd1K0ZheEJWOGJRTXh2d24vcG1SLzJCT3ZoMTNEOVRFOGV6Wmw5QjFxVzlsS2VjK2ZHQkppUHNURlZQczN5Zwp6a2FwSVBpZzNXZ2xuZFBYKzl4YXJXeWVDaGpTV2RuZW51RisrQ1hXNkRmNnRPVE5pUlpsWlU5QnFnL2JESWNBCmc3QVN6bzBibkk4Rm5mcmo3NjZoSXZveHcrOEFQY0ZKVC9wa2V5bGdlTUxCOUM2Zm14Ui9CVGZaa2ZDS0UvSlkKS1NSMnptOE9HdXFVMWw0NEJPMHVWVmpBVHBuNHNxTGE2NkxnaEpRVXRYcC9lYWxsN2JKWkNZTUUwM0VZcnJLUQpxbytnV2w1cXZxMzFqcmx5V3dOc1RTbXpNQi9XOTdFNkFXSWlQLzRvb1FLQmdRRC9pQnB3bm1NM0xmaklBbGp1CkxCckNIbWpnVjdmczJlRG5jWHlLS28vZGlZTWxyZVUwS3JNc0tIaUZ0TGdDb01TWHBvWUxnTE9PNlNGNHRWMlIKUSs1U3JHU0c5OUJFQ3lkSXIvMWp5c1pmdlc4TmFSWlNhaE5yZGpQYzF1ekJFaW51SUtzR3ZHSkp5L1duNjJ1bQoxay90MThaQlZ5UUVGNExYd2R6NVQ3eXNvd0tCZ1FDK3lkNXhyN1J4bzhod2FGNTlrdC9SSmlpNDNjYWFTRFl5CmxJVFpuSlpaMXJEMytUTWJzbm1EYm5FMnNnSzBPTUpRc05vSW12MFZ3aGorb0ZZMUNBRGpHaWxUNTNLRmhmVnoKM1FJS0lVTk9yUzNHYTRxbExpeXpsa0VMdjlJc0NJbzRIQjk3a25FVHJPQTNmcHlUZ1IvUmtUMnBzZjA3eHF3egp5K1BzYUtsUkNRS0JnUUNRMDNyb3lWeENNZlFHcUEzdkwyQWJGVkVybFl2UTJjdjJZUVBNNjBLT3RSbDNpWStXCmVYMERVZ3k4K3lndmxSN1hOTEpVWXFWaUlnK3VjbHlOc0lxcW9McDVKSXNOaGFUR05ialBqbVhRYlhVN2pJdnkKT2R5MzAwNmhvODZidnNlMUJ4N251bTJhbGRhdFRXaStMa2t1N0ZTWlErSk56MldCRTRkQ1prYnhNUUtCZ0RIawo4eEtDSTh0d1RMUHc1MzBwa3ZUTWFPdm51OCtQUVBVN1YvN2M3NGp4RjNqU0orWi9aejNTL1RLVG5SZHFuSTZqCm9YR01ydEVvNElaK2dleitlZFRxZTVKZ3ZkZGpjQXhyNk9PalRVbmZDbENRd1VKdmIrdExTUmw4Z2NkWU9HVnkKSFYyZ3I0ZTR0eTVzSXlDRUxVRU9IYlVxUWhLRzQzUHNSMkFGQXZxWkFvR0JBTVd1QmFQN1lwM2IzQU5xUlR1RQpKSFFVT1FCb3VRcXpKNnlsS1ZZYU10VGRVRi8xUTV5cE5GWWVtOGZuRlp5SjluMFVlcGdwK3p6bTZYc3JKSUZRCk1lR24waUIraS8rNFhvQ3hLQUpjbW8zTUNUdVRxVitlT2FuRHRpQWNJN2YxQ2hnMjVYV25XYnRoYWh2NEdYSWcKayt5RE5PK0lOcU02NlJCdUhuMWswemxFCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0KCg==
kind: Secret
metadata: 
  name: parts-web-secret
  namespace: default
type: kubernetes.io/tls

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-ingress-parts
spec:
  ingressClassName: nginx
  tls: 
    - 
      hosts: 
        - partsunlimited.cloudns.biz
      secretName: parts-web-secret
  rules:
  - host: partsunlimited.cloudns.biz
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: parts-web
              port:
                number: 80
  


