trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionEndpoint: 'win365enterprise-terra-deploy-rg'
<<<<<<< HEAD
  resourceGroupName: 'terra-deploy-rg'
=======
  resourceGroupName: 'k8s-test'
>>>>>>> cac3d9dfc08357f0c4ab930e41744c8a83f615c8
  storageAccountName: 'k8stestrg'

steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'v1.6.6'

  - script: |
      terraform init
      terraform plan -out=tfplan
    displayName: 'Terraform Init and Plan'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Terraform Plan'
    inputs:
      targetPath: '$(Pipeline.Workspace)/tfplan'
      artifactName: 'terraform-plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'
