apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
        - name: bookings
          image: smarthotels/bookings:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookings
spec:
  type: NodePort
  selector:
    app: bookings
  ports:
    - port: 80
      targetPort: 80
