apiVersion: apps/v1
kind: Deployment
metadata:
  name: conf
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conf
  template:
    metadata:
      labels:
        app: conf
    spec:
      containers:
        - name: conf
          image: smarthotels/configuration:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conf
spec:
  type: NodePort
  selector:
    app: conf
  ports:
    - port: 80
      targetPort: 80
