apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts
spec:
  replicas: 5
  selector:
    matchLabels:
      app: discounts
  template:
    metadata:
      labels:
        app: discounts
    spec:
      containers:
        - name: discounts
          image: smarthotels/discounts:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: discounts
spec:
  type: NodePort
  selector:
    app: discounts
  ports:
    - port: 80
      targetPort: 80
