apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
        - name: hotels
          image: smarthotels/hotels:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hotels
spec:
  type: NodePort
  selector:
    app: hotels
  ports:
    - port: 80
      targetPort: 80
