apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
spec:
  replicas: 5
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
        - name: notify
          image: smarthotels/notifications:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  type: NodePort
  selector:
    app: notify
  ports:
    - port: 80
      targetPort: 80
