apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - name: reviews
          image: smarthotels/reviews:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  type: NodePort
  selector:
    app: reviews
  ports:
    - port: 80
      targetPort: 80
