apiVersion: apps/v1
kind: Deployment
metadata:
  name: suggest
spec:
  replicas: 5
  selector:
    matchLabels:
      app: suggest
  template:
    metadata:
      labels:
        app: suggest
    spec:
      containers:
        - name: suggest
          image: smarthotels/suggestions:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: suggest
spec:
  type: NodePort
  selector:
    app: suggest
  ports:
    - port: 80
      targetPort: 80
