apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: smarthotels/tasks:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tasks
spec:
  type: NodePort
  selector:
    app: tasks
  ports:
    - port: 80
      targetPort: 80
