apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: noknok79/mongo:latest
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017


apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-order
spec:
  replicas: 5
  selector:
    matchLabels:
      app: parts-order
  template:
    metadata:
      labels:
        app: parts-order
    spec:    
      containers:
        - name: parts-order
          image: noknok79/parts-order:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: parts-order
spec:
  type: NodePort
  selector:
    app: parts-order
  ports:
    - port: 80
      targetPort: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: parts-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: parts-web
  template:
    metadata:
      labels:
        app: parts-web
    spec:
      containers:
        - name: parts-web
          image: noknok79/parts-web:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: parts-web
spec:
  type: LoadBalancer
  selector:
    app: parts-web
  ports:
    - port: 80
      targetPort: 80


