trigger:
    branches:
        include:
            - main

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: UsePythonVersion@0
        inputs:
            versionSpec: '3.x'
            addToPath: true

    - script: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        displayName: 'Install Python dependencies'

    - script: |
            terraform init
            terraform validate
        displayName: 'Initialize and validate Terraform'

    - script: |
            terraform plan -out=tfplan
        displayName: 'Generate Terraform plan'

    - script: |
            terraform apply -auto-approve tfplan
        displayName: 'Apply Terraform changes'

    - script: |
            terraform destroy -auto-approve
        displayName: 'Destroy infrastructure'

    - task: PublishPipelineArtifact@1
        inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifactName: 'terraform-artifact'
        displayName: 'Publish Terraform artifact'
