trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      docker pull <docker-image-name>:<tag>
      docker run -d <docker-image-name>:<tag>
    displayName: 'Deploy Docker image'

  - script: |
      docker-compose up -d
    displayName: 'Deploy Docker Compose'

  - script: |
      docker push <docker-image-name>:<tag>
    displayName: 'Push Docker image'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      terraform init
      terraform plan -out=tfplan
    displayName: 'Terraform Init and Plan'

  - script: |
      terraform apply -auto-approve tfplan
    displayName: 'Terraform Apply'

  - script: |
      kubectl apply -f /path/to/deployment.yaml
    displayName: 'Call Kubernetes Deployment YAML'


