apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: noknok79/azure-sql-edge:latest
          ports:
            - containerPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: port1
      port: 1401
      targetPort: 1401
    - name: port2
      port: 1433
      targetPort: 1433
